compile: 
	gcc -Wall -Werror -pedantic -o diario diario_precipitacion.c
	gcc -Wall -Werror -pedantic -o mensual mensual_precipitacion.c
	gcc -Wall -Werror -pedantic -o promedio promedio.c
	gcc -Wall -Werror -pedantic -o descarga descarga.c

clean:
	rm *.o diario
	rm *.o mensual
	rm *.o promedio
	rm *.o descarga

run: 
	
